# IO

In [1]:
from sklearnex import patch_sklearn
patch_sklearn()

Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)

In [2]:
from PineBioML import IO

In [3]:
# Path
input_folder = "./input/"
output_folder = "./output/"
export_title = "example_basic "

In [4]:
x, y = IO.read_multiple_groups(
    file_path_list=[
        input_folder+ "example_group1.csv", # all samples from this file will have y = 0, because it is in the 1st place of the file path list.
        input_folder+ "example_group2.tsv", # all samples from this file will have y = 1, because it is in the 2nd place of the file path list.
    ],
    index_col=0
    )

In [5]:
x.index = x.index.astype(str)
y.index = x.index
y = y.astype(int).astype(str)

In [6]:
y.value_counts()

label
0    100
1    100
Name: count, dtype: int64

In [7]:
target_label = '1'

# Train test split

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(x, y, test_size=0.33, random_state=142, shuffle=True, stratify=y)

In [9]:
x_train.index = x_train.index.astype(str)
x_valid.index = x_valid.index.astype(str)
y_train.index = y_train.index.astype(str)
y_valid.index = y_valid.index.astype(str)

In [10]:
x_train

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature90,feature91,feature92,feature93,feature94,feature95,feature96,feature97,feature98,feature99
171,0.551599,-0.976652,0.128228,-0.088251,1.004495,-0.315624,-1.326554,-0.177223,-0.556728,0.777672,...,0.147452,-1.082386,-0.137693,-0.262117,0.497860,1.688911,-0.002486,-1.102776,-1.371464,1.119775
194,-0.135892,-0.253460,-0.651138,0.541736,-0.618099,-0.294314,-0.487022,-0.662317,-0.527136,1.492715,...,-1.088968,0.843941,0.802761,0.058075,0.899959,-0.535979,1.602846,0.113808,1.149086,-0.490454
52,-0.087481,0.345581,0.839381,0.031559,-2.848543,0.489888,-0.729897,0.315919,0.308215,2.156980,...,1.488484,-0.302235,-2.168466,1.356787,-0.710598,0.082528,-1.149746,-0.553018,-0.235349,-2.444959
181,-1.264423,-0.801806,0.729013,-0.890166,-2.149759,-1.133124,-2.281392,-1.467906,0.534294,-0.642758,...,-0.859264,-1.035224,-0.513892,1.943910,-1.806044,-0.642353,0.915683,0.531059,-2.035915,0.740164
126,-1.811243,-0.642033,-0.622368,1.843264,1.431472,-1.052770,-1.032919,1.595245,0.572449,-0.047049,...,-0.729760,-1.718881,-0.010071,-1.419252,-1.101163,0.265964,0.126249,0.880492,-0.346363,0.704150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,-0.791376,0.581125,1.201252,-0.205969,2.004799,0.233037,0.143258,0.430896,0.756377,0.271960,...,-0.032955,2.354930,0.163021,-2.196720,1.134399,0.154438,0.151923,-2.187636,0.505085,0.081940
176,0.394617,-0.520311,0.063166,0.960240,0.385400,0.360134,1.625827,0.530870,0.220995,0.296317,...,1.699266,2.493636,-1.160023,0.433886,0.697301,0.109639,1.494909,0.839825,1.226464,0.161837
16,0.992466,-0.250265,0.932521,-0.183215,0.002164,1.267180,-0.800572,0.137752,0.507310,-0.256396,...,-2.704475,-0.546662,-1.170184,0.181370,1.058670,-0.513363,-0.369444,0.437111,-0.525440,1.412814
95,0.982804,0.111459,-0.925103,0.443304,0.246464,1.193286,-0.107172,1.633772,1.447069,-0.871689,...,-0.153710,0.892774,1.647504,-0.517333,-1.576844,-0.132580,0.950460,0.416072,-0.324131,2.044794
44,0.377525,-0.064742,-0.660915,-0.197620,1.524670,0.862431,1.010678,-0.417802,-0.650606,-0.899518,...,1.389039,-0.466183,1.894159,1.176963,-1.076268,-1.011873,-2.010354,0.943602,0.103709,-0.106572

# Experiment

In [11]:
from PineBioML.model.utils import Pine, sklearn_esitimator_wrapper, data_source

from PineBioML.preprocessing import Normalizer, Pass
from PineBioML.preprocessing.impute import knn_imputer, simple_imputer
from PineBioML.preprocessing.utils import feature_extension
from PineBioML.preprocessing.outlier import IsolationForest, simple_clip
from PineBioML.selection.classification import ensemble_selector
from PineBioML.model.supervised import Classification
from sklearn.linear_model import LogisticRegression


# define the experiment pipeline
experiment = [
    ("DataSource", {
        "first256": data_source(x_train.iloc[:, :50], x_valid.iloc[:, :50]),
        "others": data_source(x_train.iloc[:, 50:], x_valid.iloc[:, 50:])
    }),
#    ("OutlierDetection", {
 #       "Simple clip": simple_clip(),
  #      "None": Pass()}),
#    ("MissingValueProcessing", {
 #       "mean": simple_imputer(threshold=0.3333, strategy="mean")
  #  }),
    ("Standarization", {
        "StandardScaler": Normalizer(method="StandardScaler"),
    }),
    ("Selection",{
        "ensemble": ensemble_selector(z_importance_threshold=1),
        #"None": Pass()
    }),
    ("Modeling", {
        "LgisticRegression":
        sklearn_esitimator_wrapper(LogisticRegression(penalty=None)),
        "ElasticLogisticRegression":
        Classification.ElasticLogit_tuner(target="auc"),
        "rbf-SVM":
        Classification.SVM_tuner(target="acc"),
        "DecistionTree":
        Classification.DecisionTree_tuner(target="auc"),
        "RandomForest":
        Classification.RandomForest_tuner(target="auc"),
        "AdaBoost":
        Classification.AdaBoost_tuner(target="auc"),
        "XGBoost":
        Classification.XGBoost_tuner(target="auc"),
        "LightGBM":
        Classification.LightGBM_tuner(target="auc"),
    }),
]

In [12]:
pine_automl = Pine(experiment, target_label = target_label, cv_result= True, evaluate_ncv = 3)
result = pine_automl.do_experiment(x_train, y_train, x_valid, y_valid)

Using  c45  to score.

100%|██████████| 50/50 [00:03<00:00, 13.82it/s]
100%|██████████| 50/50 [00:00<00:00, 3538.12it/s]
100%|██████████| 50/50 [00:00<00:00, 3696.66it/s]
100%|██████████| 50/50 [00:00<00:00, 3829.65it/s]
100%|██████████| 50/50 [00:00<00:00, 3699.86it/s]

c45  is done. Using 3.7695

Using  RF_gini  to score.
RF_gini  is done. Using 1.5764

Using  Lasso  to score.
Lasso  is done. Using 0.0341

Using  multi_Lasso  to score.
multi_Lasso  is done. Using 0.1040

Using  SVM  to score.
SVM  is done. Using 0.0130

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

optuna seed 15031  |  validation seed 12601  |  model seed 14770
    ElasticNetLogisticRegression start tuning. it will take a while.
    optuna is better, best trial:  11
optuna seed 16154  |  validation seed 13740  |  model seed 1457
    SVM start tuning. it will take a while.

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(

    optuna is better, best trial:  24
optuna seed 13747  |  validation seed 8246  |  model seed 7409
    DecisionTree start tuning. it will take a while.
    optuna is better, best trial:  16
optuna seed 4231  |  validation seed 10592  |  model seed 5926
    RandomForest start tuning. it will take a while.

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\onedal\ensemble\forest.py:346: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warnings.warn(

    optuna is better, best trial:  30

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

optuna seed 2156  |  validation seed 4794  |  model seed 1479
    AdaBoost start tuning. it will take a while.
    optuna is better, best trial:  18

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

optuna seed 5612  |  validation seed 2895  |  model seed 15746
    XGBoost start tuning. it will take a while.
    optuna is better, best trial:  66
optuna seed 4076  |  validation seed 12678  |  model seed 7428
    LightGBM start tuning. it will take a while.

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

    optuna is better, best trial:  0
Using  c45  to score.

100%|██████████| 50/50 [00:00<00:00, 1952.02it/s]
100%|██████████| 50/50 [00:00<00:00, 1563.38it/s]
100%|██████████| 50/50 [00:00<00:00, 1231.48it/s]
100%|██████████| 50/50 [00:00<00:00, 2701.47it/s]
100%|██████████| 50/50 [00:00<00:00, 2377.78it/s]

c45  is done. Using 0.2331

Using  RF_gini  to score.
RF_gini  is done. Using 0.3278

Using  Lasso  to score.
Lasso  is done. Using 0.0335

Using  multi_Lasso  to score.
multi_Lasso  is done. Using 0.1130

Using  SVM  to score.
SVM  is done. Using 0.0130

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

optuna seed 15031  |  validation seed 12601  |  model seed 14770
    ElasticNetLogisticRegression start tuning. it will take a while.
    optuna is better, best trial:  16
optuna seed 16154  |  validation seed 13740  |  model seed 1457
    SVM start tuning. it will take a while.

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(
c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearnex\svm\_common.py:312: RuntimeWarning: random_state does not influence oneDAL SVM results
  warnings.warn(

    optuna is better, best trial:  17
optuna seed 13747  |  validation seed 8246  |  model seed 7409
    DecisionTree start tuning. it will take a while.
    optuna is better, best trial:  13
optuna seed 4231  |  validation seed 10592  |  model seed 5926
    RandomForest start tuning. it will take a while.

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

    optuna is better, best trial:  37

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

optuna seed 2156  |  validation seed 4794  |  model seed 1479
    AdaBoost start tuning. it will take a while.
    optuna is better, best trial:  14
optuna seed 5612  |  validation seed 2895  |  model seed 15746
    XGBoost start tuning. it will take a while.

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

    optuna is better, best trial:  65
optuna seed 4076  |  validation seed 12678  |  model seed 7428
    LightGBM start tuning. it will take a while.

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

    optuna is better, best trial:  5

In [13]:
pine_automl.experiment_detail()

,parameter,dtype,lower_bound,upper_bound,result
ElasticNetLogisticRegression,None,None,None,None,None
,C,float,0.000001,100.0,20.581842
,l1_ratio,float,-0.5,1.5,0.246883
SVM,None,None,None,None,None
,kernel,category,"[linear, poly, rbf, sigmoid]",None,sigmoid
,C,float,0.011576,1157.58369,0.451079
DecisionTree,None,None,None,None,None
,max_depth,int,4,9,9.0
,min_samples_leaf,int,1,6,3.0
,ccp_alpha,float,0.000075,0.746269,0.000631
RandomForest,None,None,None,None,None
,n_estimators,int,32,512,88.0
,min_samples_leaf,int,1,6,1.0
,ccp_alpha,float,0.000075,0.746269,0.000301
,max_samples,float,0.4,0.8,0.591383
,max_depth,int,4,9,8.0
AdaBoost,None,None,None,None,None
,n_estimators,int,4,64,12.0
,learning_rate,float,0.01,1.0,0.160934
XGBoost,None,None,None,None,None
,n_estimators,int,4,256,13.0
,max_depth,int,4,14,9.0
,gamma,float,0.0001,0.01,0.003032
,min_child_weight,float,1,6,4.974258
,learning_rate,float,0.01,1.0,0.365075
,subsample,float,0.5,1,0.548267
,colsample_bytree,float,0.5,1,0.675488
,reg_lambda,float,0.0001,1,0.000335
,reg_alpha,float,0.0001,1.0,0.04719
LightGBM,None,None,None,None,None
,n_estimators,int,4,256,20.0
,max_depth,int,4,14,14.0
,min_child_samples,int,1,6,1.0
,learning_rate,float,0.01,1.0,0.092084
,subsample,float,0.5,1.0,0.81486
,colsample_bytree,float,0.5,1.0,0.504927
,reg_lambda,float,0.0001,1,0.000531
,reg_alpha,float,0.0001,1.0,0.007479

In [14]:
# print the results, sort according to test_auc
result = result.sort_values("cv_auc")

In [15]:
pine_automl.experiment_results(timer = True).iloc[:, :12]

,DataSource,Standarization,Selection,Modeling,DataSource_time,Standarization_time,Selection_time,Modeling_fit_time,Modeling_predict_time,train_sensitivity,train_f1,train_specificity
0,first256,StandardScaler,ensemble,LgisticRegression,0.0,0.005021,5.502007,0.004229,0.001110,0.656716,0.647059,0.626866
1,first256,StandardScaler,ensemble,ElasticLogisticRegression,0.0,0.005021,5.502007,0.739895,0.000000,0.656716,0.647059,0.626866
2,first256,StandardScaler,ensemble,rbf-SVM,0.0,0.005021,5.502007,1.614707,0.002105,0.701493,0.661972,0.582090
3,first256,StandardScaler,ensemble,DecistionTree,0.0,0.005021,5.502007,0.689501,0.000000,0.835821,0.783217,0.701493
4,first256,StandardScaler,ensemble,RandomForest,0.0,0.005021,5.502007,8.715575,0.039931,0.791045,0.796992,0.805970
5,first256,StandardScaler,ensemble,AdaBoost,0.0,0.005021,5.502007,5.023196,0.004997,0.910448,0.748466,0.477612
6,first256,StandardScaler,ensemble,XGBoost,0.0,0.005021,5.502007,9.215499,0.001000,0.835821,0.756757,0.626866
7,first256,StandardScaler,ensemble,LightGBM,0.0,0.005021,5.502007,4.831059,0.001000,0.820896,0.791367,0.746269
8,others,StandardScaler,ensemble,LgisticRegression,0.0,0.003000,0.723395,0.003755,0.001099,0.537313,0.553846,0.597015
9,others,StandardScaler,ensemble,ElasticLogisticRegression,0.0,0.003000,0.723395,0.828163,0.001002,0.537313,0.553846,0.597015
10,others,StandardScaler,ensemble,rbf-SVM,0.0,0.003000,0.723395,2.385221,0.001008,0.507463,0.523077,0.567164
11,others,StandardScaler,ensemble,DecistionTree,0.0,0.003000,0.723395,0.763987,0.001000,0.865672,0.846715,0.820896
12,others,StandardScaler,ensemble,RandomForest,0.0,0.003000,0.723395,6.306514,0.018654,0.955224,0.962406,0.970149
13,others,StandardScaler,ensemble,AdaBoost,0.0,0.003000,0.723395,3.053933,0.002002,0.402985,0.524272,0.865672
14,others,StandardScaler,ensemble,XGBoost,0.0,0.003000,0.723395,9.882701,0.002003,0.731343,0.710145,0.671642
15,others,StandardScaler,ensemble,LightGBM,0.0,0.003000,0.723395,4.079473,0.001002,1.000000,1.000000,1.000000

In [16]:
pine_automl.experiment_results(std = True).iloc[:, -12:]

,test_specificity,test_auc,test_mcc,test_accuracy,test_support,cv_sensitivity_std,cv_f1_std,cv_specificity_std,cv_auc_std,cv_mcc_std,cv_accuracy_std,cv_support_std
0,0.606061,0.755739,0.367884,0.681818,66,0.123107,0.066034,0.132608,0.081272,0.090030,0.047872,0.57735
1,0.606061,0.755739,0.367884,0.681818,66,0.123107,0.066034,0.132608,0.081272,0.090030,0.047872,0.57735
2,0.484848,0.755739,0.286183,0.636364,66,0.123107,0.066034,0.132608,0.081272,0.090030,0.047872,0.57735
3,0.757576,0.749311,0.485071,0.742424,66,0.032614,0.025903,0.134769,0.025433,0.114453,0.056029,0.57735
4,0.787879,0.770432,0.486864,0.742424,66,0.057596,0.052140,0.035150,0.072714,0.085486,0.042971,0.57735
5,0.424242,0.727273,0.424264,0.681818,66,0.069900,0.028902,0.062755,0.032807,0.061087,0.028103,0.57735
6,0.727273,0.768595,0.454545,0.727273,66,0.267072,0.126469,0.164095,0.103374,0.138249,0.059978,0.57735
7,0.606061,0.730946,0.335809,0.666667,66,0.077024,0.068906,0.036028,0.037430,0.113361,0.056767,0.57735
8,0.575758,0.521579,0.060858,0.530303,66,0.137921,0.064541,0.154315,0.062217,0.113378,0.052224,0.57735
9,0.575758,0.521579,0.060858,0.530303,66,0.137921,0.064541,0.154315,0.062217,0.113378,0.052224,0.57735
10,0.484848,0.496786,-0.030303,0.484848,66,0.125412,0.052125,0.146356,0.064294,0.081423,0.038543,0.57735
11,0.454545,0.525712,0.030528,0.515152,66,0.078415,0.072773,0.081396,0.088506,0.123369,0.061195,0.57735
12,0.393939,0.478421,-0.091584,0.454545,66,0.091366,0.055732,0.126008,0.049696,0.106643,0.054136,0.57735
13,0.818182,0.486685,0.108465,0.545455,66,0.386586,0.317188,0.326502,0.077934,0.129477,0.035823,0.57735
14,0.454545,0.511938,0.124035,0.560606,66,0.137049,0.086124,0.192790,0.091670,0.165134,0.075237,0.57735
15,0.454545,0.520661,0.000000,0.500000,66,0.059759,0.020515,0.069602,0.028664,0.019971,0.008165,0.57735

In [17]:
# save the result
result.to_csv("./output/example_Pine_result.csv")

# Pick a model and save it

In [18]:
# notice that the model is not fitted yet
model = pine_automl.recall_model(id = result.index[-1])

In [19]:
# fit the model
model.fit(x_train, y_train)
y_valid_prob = model.predict_proba(x_valid)

Using  c45  to score.

100%|██████████| 50/50 [00:00<00:00, 1637.73it/s]
100%|██████████| 50/50 [00:00<00:00, 1611.15it/s]
100%|██████████| 50/50 [00:00<00:00, 2076.76it/s]
100%|██████████| 50/50 [00:00<00:00, 2030.43it/s]
100%|██████████| 50/50 [00:00<00:00, 2119.34it/s]

c45  is done. Using 0.2331

Using  RF_gini  to score.
RF_gini  is done. Using 0.3901

Using  Lasso  to score.
Lasso  is done. Using 0.0341

Using  multi_Lasso  to score.
multi_Lasso  is done. Using 0.1120

Using  SVM  to score.
SVM  is done. Using 0.0130

optuna seed 5612  |  validation seed 2895  |  model seed 15746
    XGBoost start tuning. it will take a while.

c:\Users\aimhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(

    optuna is better, best trial:  66

### summary

In [20]:
from shap.plots import beeswarm

beeswarm(model[-1].shap_explain(model[:-1].transform(x_valid))[:,:1])

AttributeError: The following error was raised: 'ensemble_selector' object has no attribute '__sklearn_tags__'. It seems that there are no classes that implement `__sklearn_tags__` in the MRO and/or all classes in the MRO call `super().__sklearn_tags__()`. Make sure to inherit from `BaseEstimator` which implements `__sklearn_tags__` (or alternatively define `__sklearn_tags__` but we don't recommend this approach). Note that `BaseEstimator` needs to be on the right side of other Mixins in the inheritance order.

In [ ]:
from PineBioML.report.utils import classification_summary

classification_summary(y_valid, y_valid_prob, target_label=target_label, save_fig=True, save_path="./output/images")

### save the model

IO.save_model(model, "./output/models/", "mode0", overide=True)